name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[test,browser]
          pip install pytest-asyncio structlog pytest-cov

      - name: Run tests
        run: |
          pytest --cov=web_search_sdk --cov-report=xml --cov-report=term --cov-fail-under=0 -q

      - name: Execute demo notebook (offline mode)
        env:
          OFFLINE_MODE: "1"
        run: |
          python scripts/run_demo.py

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml 