name: CI

on:
  push:
    paths:
      - 'Data_Mining/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'Data_Mining/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install core dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e Data_Mining[test]  # installs pytest deps

      - name: Install browser extras (optional)
        run: pip install -e Data_Mining[browser]

      - name: Setup geckodriver
        uses: browser-actions/setup-geckodriver@v1
        with:
          version: latest

      - name: Run tests + coverage
        env:
          USE_BROWSER: '1'
        run: |
          pytest -c Data_Mining/pytest.ini \
            --cov=Data_Mining --cov-config=Data_Mining/.coveragerc -q

      - name: Build HTML docs with pdoc
        run: |
          pip install pdoc3
          pdoc -o docs_html Data_Mining 